"""Create table chanch

Revision ID: 103a5ad96a6b
Revises: 
Create Date: 2024-09-20 17:14:28.570608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '103a5ad96a6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ATR', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('PPG', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('PPG')
        batch_op.drop_column('ATR')

    # ### end Alembic commands ###
